version: '3'

services:

    laravel:
        restart: always
        environment:
          - MAX_PHP_PROCESS=5
          - NGINX_PROCESS=1
        env_file: .env
        build:
            context: ./
        ports:
            - "80:80"