version: '3.7'

services:

  minio:
    image: minio/minio:RELEASE.2020-11-25T22-36-25Z
    volumes:
      - data1-1:/data
    ports:
      - "9090:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    networks:
      - laravel-net

networks:
  laravel-net:
    external: true

volumes:
  data1-1: