version: '3.7'

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="secret"
      - MYSQL_DATABASE="agendadb"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-net

  adminer:
    image: adminer:4.7.1-fastcgi
    ports:
      - "8080:8080"
    command:
      - "php"
      - "-S"
      - "0.0.0.0:8080"
      - "-t"
      - "/var/www/html"
    environment:
      - "ADMINER_DEFAULT_SERVER=mysql"
      - "ADMINER_DESIGN=pepa-linha"
      - "ADMINER_PLUGINS=tinymce"
      - "PHP_POST_MAX_SIZE=512M"
      - "PHP_UPLOAD_MAX_FILESIZE=512M"
    networks:
      - laravel-net

networks:
  laravel-net:
    external: true

volumes:
  mysql_data:
